const $=(s,r=document)=>r.querySelector(s);
const cards=(a,f,c='')=>`<div class="grid ${c}">${a.map((x,i)=>`<div class="card rv tilt"${c?' tabindex="0"':''}>${f(x,i)}</div>`).join('')}</div>`;
const head=(l,t,p)=>`<span class="lab">${l}</span><h2>${t}</h2>${p?`<p style="max-width:720px">${p}</p>`:''}`;
const ctaBlock=(h,p,b1,b2)=>`<div class="cta rv"><h2>${h}</h2><p style="max-width:560px;margin:0 auto 24px">${p}</p>${b1?`<a class="btn mag" href="#contact">${b1}</a>`:''}${b2?` <a class="btn o mag" style="color:#fff;border-color:#fff5" href="mailto:marketiqo016@gmail.com">${b2}</a>`:''}</div>`;
const problems=[['🔍','Low search visibility'],['🧩','Inconsistent digital presence'],['📉','Poor website traffic'],['📢','Weak brand awareness'],['🎯','Unqualified leads'],['💬','Low engagement'],['⚙️','Ineffective campaigns'],['🔄','Poor conversion rates'],['🧭','Lack of a clear digital strategy']];
const steps=[['Research','Understand your market, audience and competitors.'],['Strategy','Turn objectives into a focused marketing roadmap.'],['Execution','Launch SEO, content and campaigns with care.'],['Analysis','Read the data to see what is working.'],['Optimization','Test and refine to improve performance.'],['Growth','Build momentum that compounds over time.']];
const why=[['🧠','Strategy First','We start with business objectives, audience research, and market understanding before building campaigns.'],['📊','Data-Driven','We use meaningful performance data to understand what works and where opportunities exist.'],['🔎','SEO-Focused','We build search visibility through structured, sustainable SEO strategies.'],['💡','Creative Thinking','We combine marketing strategy with creative ideas that help brands stand out.'],['🤝','Customer-Centric','We focus on understanding the audience and creating experiences that connect with them.'],['🚀','Growth Mindset','We continuously analyze, test, and optimize to improve digital performance.']];
const journey=['Brand','Visibility','Traffic','Engagement','Leads','Conversions','Growth'];
const values=[['⚖️','Integrity','Honest advice and clear communication, always.'],['🔭','Curiosity','We keep asking why, and keep learning.'],['🎨','Creativity','Ideas that make brands worth noticing.'],['📈','Data','Decisions grounded in meaningful evidence.'],['💜','Customer Success','Your goals define how we measure our work.'],['♻️','Continuous Improvement','Every campaign teaches us something.']];
const svc=[['Digital Marketing Strategy','Develop clear digital strategies based on business objectives, market research, audience behavior, and competitive positioning.',[]],['SEO','Improve organic search visibility through:',['Keyword research','On-page SEO','Technical SEO','Content optimization','SEO audits','Search intent strategy','Link-building strategy','Local SEO where appropriate']],['Social Media Marketing','Build stronger social presence through:',['Social strategy','Content planning','Audience engagement','Campaign development','Brand communication','Performance analysis']],['Performance Marketing','Create and optimize paid campaigns across appropriate advertising platforms.',['Campaign strategy','Audience targeting','Ad creative direction','Campaign optimization','Performance tracking','Conversion analysis']],['Content Marketing','Strategic content designed to attract, educate, engage, and convert the right audience.',['Content strategy','Blog content','SEO content','Website copy','Social content','Educational content']],['Lead Generation','Build digital strategies designed to attract relevant prospects and create opportunities for businesses.',[]],['Brand & Digital Presence','Help businesses build a consistent and professional digital identity across their website, search presence, social platforms, and digital channels.',[]],['Analytics & Reporting','Use marketing data to understand performance and identify opportunities.',['Marketing analytics','SEO reporting','Campaign reporting','KPI tracking','Performance insights','Optimization recommendations']],['Conversion Optimization','Improve digital experiences to help businesses turn relevant traffic into meaningful actions.',['Landing page optimization','CTA optimization','User journey analysis','Messaging optimization','Conversion analysis']]];
const how=[['Discover','Understand the business.'],['Strategize','Build the marketing roadmap.'],['Create','Develop campaigns and content.'],['Launch','Put the strategy into action.'],['Measure','Track meaningful performance.'],['Optimize','Improve continuously.']];
const cats={SEO:'🔎',"Digital Marketing":'🧭',"Social Media":'💬',"Paid Advertising":'🎯',"Content Marketing":'✍️',Analytics:'📊',Conversion:'🔄'};
const posts=[['SEO','SEO Fundamentals: Where to Start','A plain-language introduction to how search visibility works.','6 min'],['SEO','Keyword Research and Search Intent','Matching your content to what people actually want.','7 min'],['Digital Marketing','Building a Digital Marketing Plan','From objectives to channels to a workable roadmap.','8 min'],['Digital Marketing','Understanding the Customer Journey','Mapping the steps from first impression to action.','6 min'],['Social Media','Social Strategy That Supports Business Goals','Planning content and engagement with purpose.','5 min'],['Paid Advertising','Google Ads Basics for Businesses','How campaigns, audiences and budgets fit together.','7 min'],['Content Marketing','Content Strategy in Practice','Planning content that attracts and educates.','6 min'],['Analytics','Marketing Metrics and KPIs That Matter','Choosing measures that reflect real objectives.','6 min'],['Conversion','Landing Pages and CTAs','Small changes that clarify the next step.','5 min']];
const cols=['#2563eb','#3b82f6','#0ea5e9','#e879f9'];
const pages={
home:()=>`<section class="hero full"><div class="w"><div><span class="lab">MARKETIQO — Digital Growth Agency</span><h1>WE TURN DIGITAL ATTENTION INTO <span class="gt">MEASURABLE GROWTH.</span></h1><p style="font-size:1.2rem;max-width:820px">MARKETIQO is a digital marketing agency helping businesses build stronger brands, increase online visibility, reach the right audience, and turn digital strategy into meaningful growth.</p><div class="pl"><span>Problem</span><b>→</b><span>Strategy</span><b>→</b><span>Growth</span></div></div>
</div></section>
<div class="script rv" aria-hidden="true">Marketiqo</div>
<section><div class="w">${head('The problem','YOUR BUSINESS IS ONLINE. BUT IS IT BEING FOUND?',"In today's digital landscape, having an online presence isn't enough. Businesses often struggle with:")}<div style="height:24px"></div>${cards(problems,(p,i)=>`<span class="num">${String(i+1).padStart(2,'0')}</span><h3>${p[1]}</h3><i class="bar"></i>`,'pcards')}<p style="margin-top:24px;max-width:760px">MARKETIQO helps businesses identify these challenges and build focused digital strategies designed around their goals, audience, and market.</p></div></section>
<section><div class="w">${head('The solution','WE TURN MARKETING CHALLENGES INTO GROWTH OPPORTUNITIES.','MARKETIQO combines strategy, creativity, technology, SEO, content, performance marketing, and data to create digital growth systems that help businesses compete and grow online.')}<div class="path">${steps.map((s,i)=>`<div class="st rv" tabindex="0"><div class="dot">${i+1}</div><h3>${s[0].toUpperCase()}</h3><p>${s[1]}</p></div>`).join('')}</div></div></section>
<section><div class="w">${head('Why us','WHY MARKETIQO?')}${cards(why,(w,i)=>`<span class="num">${String(i+1).padStart(2,'0')}</span><h3>${w[1].toUpperCase()}</h3><p>${w[2]}</p>`,'wcards')}</div></section>
<section><div class="w" style="max-width:560px;text-align:center">${head('Marketing growth','FROM VISIBILITY TO GROWTH')}<div class="funnel">${journey.map((j,i)=>`${i?'<div class="ar"></div>':''}<div class="fn rv" style="width:${100-i*8}%">${j.toUpperCase()}</div>`).join('')}</div></div></section>
${ctaBlock('READY TO TURN YOUR DIGITAL PRESENCE INTO A GROWTH ENGINE?',"Let's build a smarter digital marketing strategy for your business.",'','')}`,
about:()=>`<section class="hero"><div class="w"><div><span class="lab">About</span><h1>WE ARE <span class="gt">MARKETIQO.</span></h1><p style="font-size:1.05rem">MARKETIQO is a digital marketing agency focused on helping businesses build stronger digital identities, improve online visibility, connect with the right audiences, and create sustainable growth opportunities.</p><p>Founded by <b style="color:var(--tx)">ADAPALA RAMU</b>, MARKETIQO brings together digital marketing strategy, SEO, content, performance marketing, analytics, and creative thinking.</p></div><div class="scene glossy" style="height:300px"><div class="ring r1"></div><div class="ring r2"></div><div class="orb2"></div><div class="fc" style="left:4%;top:10%">Strategy</div><div class="fc" style="right:4%;top:18%;animation-delay:-2s">Creativity</div><div class="fc" style="left:18%;bottom:8%;animation-delay:-4s">Growth</div></div></div></section>
<section><div class="w"><div class="grid"><div class="card rv tilt">${head('Mission','OUR MISSION','To help businesses navigate the digital world with clear strategy, meaningful creativity, and data-driven marketing that creates measurable opportunities for growth.')}</div><div class="card rv tilt">${head('Vision','OUR VISION','To build a trusted digital marketing agency that helps ambitious businesses transform their online presence into a powerful engine for sustainable growth.')}</div></div></div></section>
<section><div class="w">${head('Our story','THE STORY BEHIND MARKETIQO','Click any text below to edit it. Add real dates and milestones when ready.')}<div class="tl" style="margin-top:24px">${[['THE IDEA','The beginning of MARKETIQO and the belief that digital marketing should be strategic, measurable, and focused on business outcomes.'],['THE APPROACH','Combining SEO, digital strategy, content, performance marketing, analytics, and creative thinking.'],['THE JOURNEY','Growing MARKETIQO into a modern digital marketing partner for businesses looking to strengthen their digital presence.']].map(t=>`<div class="card rv"><h3 contenteditable="true">${t[0]}</h3><p contenteditable="true">${t[1]}</p></div>`).join('')}</div></div></section>
<section><div class="w">${head('Our values','WHAT WE BELIEVE IN')}${cards(values,(v,i)=>`<span class="num">${String(i+1).padStart(2,'0')}</span><h3>${v[1].toUpperCase()}</h3><p>${v[2]}</p><i class="bar"></i>`,'vcards')}</div></section>
${ctaBlock('YOUR NEXT GROWTH MOVE COULD START WITH ONE CONVERSATION.',"Let's explore what MARKETIQO can do for your digital presence.",'','')}`,
services:()=>`<section class="hero"><div class="w" style="display:block;max-width:900px"><span class="lab">MARKETIQO Marketing Agency Services</span><h1>MARKETING THAT <span class="gt">MOVES YOUR BUSINESS FORWARD.</span></h1><p style="font-size:1.1rem">From search visibility to digital campaigns, MARKETIQO builds connected marketing strategies designed around your business goals.</p></div></section>
<section style="padding-top:20px"><div class="w rows">${cards(svc,(s,i)=>`<span class="num">0${i+1} —</span><h3>${s[0].toUpperCase()}</h3><p>${s[1]}</p>${s[2].length?`<ul>${s[2].map(x=>`<li>${x}</li>`).join('')}</ul>`:''}`)}</div></section>
<section><div class="w">${head('Process','HOW WE WORK')}<div class="path">${how.map((s,i)=>`<div class="st rv"><div class="dot">${i+1}</div><h3>${s[0].toUpperCase()}</h3><p style="max-height:none;opacity:1">${s[1]}</p></div>`).join('')}</div></div></section>
${ctaBlock('READY TO TURN YOUR DIGITAL PRESENCE INTO A GROWTH ENGINE?',"Let's build a smarter digital marketing strategy for your business.",'Book a consultation')}`,
blog:()=>`<section class="hero"><div class="w" style="display:block;max-width:900px"><span class="lab">Blog</span><h1>MARKETING INSIGHTS FOR <span class="gt">THE DIGITAL WORLD.</span></h1><p style="font-size:1.1rem">Practical insights, strategies, and educational resources to help businesses understand digital marketing and make smarter decisions.</p></div></section>
<section style="padding-top:20px"><div class="w">${head('Blog purpose','LEARN. APPLY. GROW.','The MARKETIQO blog exists to simplify digital marketing and provide useful knowledge businesses and marketers can apply in the real world.')}<div style="margin:24px 0" id="cf"><button class="pill b on" data-c="">All</button>${Object.keys(cats).map(c=>`<button class="pill b" data-c="${c}">${c}</button>`).join('')}</div><div class="grid" id="pg">${posts.map((p,i)=>`<div class="card rv tilt" data-c="${p[0]}"><div class="art" style="--c1:${cols[i%4]}88;--c2:${cols[(i+2)%4]}66">${cats[p[0]]}</div><span class="pill">${p[0]}</span><h3>${p[1]}</h3><p style="font-size:.92rem">${p[2]}</p><div class="meta">${p[3]} read · Sep 2026</div><a class="btn o sm" style="margin-top:14px" href="#contact">Read article</a></div>`).join('')}</div><p class="meta" style="margin-top:20px">Sample article cards. Replace with published articles, dates and images.</p></div></section>`,
contact:()=>`<section class="hero"><div class="w" style="display:block;max-width:900px"><span class="lab">Contact</span><h1>LET'S TALK ABOUT YOUR NEXT <span class="gt">GROWTH OPPORTUNITY.</span></h1><p style="font-size:1.1rem">Have a marketing challenge, a new project, or simply want to understand where your digital presence can improve? Let's start a conversation.</p></div></section>
<section style="padding-top:20px"><div class="w"><div class="grid ccards"><div class="card rv tilt"><span class="ic">✉️</span><h3>EMAIL US</h3><p style="color:var(--tx);overflow-wrap:anywhere">marketiqo016@gmail.com</p><a class="btn mag" href="mailto:marketiqo016@gmail.com">Send an email</a></div><div class="card rv tilt"><span class="ic">📷</span><h3>INSTAGRAM</h3><p style="color:var(--tx)">@marketiqo_official</p><a class="btn mag" target="_blank" rel="noopener" href="https://www.instagram.com/marketiqo_official">Follow on Instagram</a></div><div class="card rv tilt"><span class="ic">𝕏</span><h3>TWITTER</h3><p style="color:var(--tx)">@marketiqooff</p><a class="btn mag" target="_blank" rel="noopener" href="https://twitter.com/marketiqooff">Follow on Twitter</a></div><div class="card rv tilt"><span class="ic">🗓️</span><h3>CONSULTATION</h3><p>Let's discuss your business and explore potential digital marketing opportunities.</p><a class="btn mag" href="#fm" onclick="event.preventDefault();$('#fm').scrollIntoView({behavior:'smooth'});$('#fm input').focus()">Book a consultation</a></div></div>
<div class="card rv" id="fm" style="margin-top:40px;max-width:820px;margin-inline:auto"><form id="f"><div><label>Name</label><input required name="name"></div><div><label>Email</label><input required type="email" name="email"></div><div><label>Phone</label><input type="tel" name="phone"></div><div><label>Company</label><input name="company"></div><div><label>Website</label><input name="website" placeholder="https://"></div><div><label>Service interested in</label><select name="service">${['Digital Marketing','SEO','Social Media Marketing','Performance Marketing','Content Marketing','Lead Generation','Analytics','Conversion Optimization','Other'].map(o=>`<option>${o}</option>`).join('')}</select></div><div class="f"><label>Budget range (optional)</label><input name="budget"></div><div class="f"><label>Message</label><textarea rows="5" name="message"></textarea></div><div style="position:absolute;left:-9999px" aria-hidden="true"><input name="hp" tabindex="-1" autocomplete="off"></div><div class="f"><button class="btn mag" type="submit">Send inquiry</button></div><p class="f" id="ferr" role="alert" style="display:none;color:#ff8a8a;margin:0"></p></form><div class="ok" id="ok"><div style="font-size:2.4rem">✅</div><h2>Thank you. Your inquiry is in.</h2><p>We'll review your message and get back to you soon.</p></div></div></div></section><div class="script rv" aria-hidden="true" style="opacity:.4">Say hello</div>
${ctaBlock('YOUR NEXT GROWTH MOVE COULD START WITH ONE CONVERSATION.',"Let's explore what MARKETIQO can do for your digital presence.",'','')}`};
function fx(){
 const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});
 document.querySelectorAll('.rv').forEach(e=>io.observe(e));
 
}
function go(){
 const h=(location.hash||'#home').slice(1),k=pages[h]?h:'home';
 $('#app').innerHTML=`<div class="page">${pages[k]()}</div>`;
 document.querySelectorAll('.links a').forEach(a=>a.classList.toggle('on',a.getAttribute('href')==='#'+k));
 $('#ln').classList.remove('o');scrollTo(0,0);fx();
 const cf=$('#cf');if(cf)cf.onclick=e=>{const b=e.target.closest('button');if(!b)return;cf.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));document.querySelectorAll('#pg .card').forEach(c=>c.style.display=!b.dataset.c||c.dataset.c===b.dataset.c?'':'none')};
 const f=$('#f');if(f)f.onsubmit=submitForm;
}
const DF='<defs><linearGradient id="ag" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#0b3556"/><stop offset="1" stop-color="#159a9c"/></linearGradient><linearGradient id="gb" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#14b8a6"/><stop offset="1" stop-color="#0ea5e9"/></linearGradient></defs>';
const br=(x,y,w,h)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="#fff" stroke="#cbd5e1"/><circle cx="${x+16}" cy="${y+16}" r="4" fill="#f87171"/><circle cx="${x+30}" cy="${y+16}" r="4" fill="#fbbf24"/><circle cx="${x+44}" cy="${y+16}" r="4" fill="#34d399"/>`;
const sv=(b,h=300)=>`<svg viewBox="0 0 600 ${h}" role="img" aria-label="Illustration" style="width:100%;height:auto;display:block;border-radius:18px">${DF}<rect width="600" height="${h}" fill="url(#ag)"/>${b}</svg>`;
const ART=[
`${br(80,30,440,240)}<g fill="url(#gb)"><rect x="120" y="190" width="40" height="50" rx="5"/><rect x="180" y="160" width="40" height="80" rx="5"/><rect x="240" y="130" width="40" height="110" rx="5"/><rect x="300" y="100" width="40" height="140" rx="5"/></g><polyline points="140,170 200,140 260,115 320,85 460,62" fill="none" stroke="#0f172a" stroke-width="4" stroke-linecap="round"/><circle cx="460" cy="62" r="9" fill="#0ea5e9"/><rect x="380" y="130" width="110" height="12" rx="6" fill="#cbd5e1"/><rect x="380" y="152" width="80" height="12" rx="6" fill="#e2e8f0"/><rect x="380" y="185" width="110" height="34" rx="10" fill="url(#gb)"/>`,
`<path d="M150 40h300L340 150v70l-80 30v-100z" fill="url(#gb)" opacity=".9"/><g fill="#0f172a"><circle cx="210" cy="24" r="7"/><circle cx="300" cy="18" r="7"/><circle cx="390" cy="26" r="7"/></g><g fill="#2563eb"><circle cx="180" cy="270" r="14"/><circle cx="300" cy="278" r="14"/><circle cx="420" cy="270" r="14"/></g><g fill="#fff" stroke="#cbd5e1"><rect x="470" y="70" width="90" height="56" rx="10"/></g><rect x="482" y="84" width="50" height="8" rx="4" fill="#94a3b8"/><rect x="482" y="102" width="66" height="8" rx="4" fill="#0ea5e9"/>`,
`<g fill="url(#gb)"><path d="M100 40h400l-40 50H140z"/><path d="M150 100h300l-36 50H186z" opacity=".85"/><path d="M200 160h200l-30 50H230z" opacity=".7"/><rect x="250" y="220" width="100" height="42" rx="10" opacity=".55"/></g><g fill="#fff" font-family="sans-serif" font-size="15" font-weight="700" text-anchor="middle"><text x="300" y="72">AWARENESS</text><text x="300" y="132">INTEREST</text><text x="300" y="190">DECISION</text><text x="300" y="246">CUSTOMER</text></g>`,
`${br(40,40,230,220)}${br(330,40,230,220)}<circle cx="130" cy="130" r="30" fill="none" stroke="#2563eb" stroke-width="8"/><line x1="152" y1="152" x2="182" y2="182" stroke="#2563eb" stroke-width="8" stroke-linecap="round"/><rect x="80" y="200" width="150" height="12" rx="6" fill="#cbd5e1"/><rect x="380" y="90" width="130" height="90" rx="12" fill="url(#gb)"/><path d="M445 160l-22-20a14 14 0 0 1 22-16 14 14 0 0 1 22 16z" fill="#fff"/><rect x="380" y="200" width="130" height="12" rx="6" fill="#cbd5e1"/><circle cx="300" cy="150" r="24" fill="#0f172a"/><text x="300" y="156" fill="#fff" font-family="sans-serif" font-size="14" font-weight="700" text-anchor="middle">VS</text>`,
`${br(90,30,420,240)}<rect x="130" y="80" width="230" height="16" rx="8" fill="#0f172a"/><rect x="130" y="108" width="180" height="16" rx="8" fill="#0f172a"/><rect x="130" y="140" width="250" height="10" rx="5" fill="#cbd5e1"/><rect x="130" y="158" width="210" height="10" rx="5" fill="#e2e8f0"/><rect x="130" y="192" width="130" height="38" rx="10" fill="url(#gb)"/><rect x="390" y="80" width="90" height="150" rx="10" fill="#e0f2fe"/><path d="M250 225l6 22 8-9 9 14 6-4-9-14 12-2z" fill="#0f172a"/>`];
const MINI=[
`<g fill="#fff" stroke="#cbd5e1"><rect x="60" y="30" width="480" height="140" rx="14"/></g><g fill="url(#gb)"><rect x="100" y="110" width="36" height="40" rx="5"/><rect x="160" y="90" width="36" height="60" rx="5"/><rect x="220" y="70" width="36" height="80" rx="5"/><rect x="280" y="52" width="36" height="98" rx="5"/></g><rect x="360" y="60" width="140" height="12" rx="6" fill="#cbd5e1"/><rect x="360" y="86" width="100" height="12" rx="6" fill="#e2e8f0"/>`,
`<g fill="none" stroke="#2563eb" stroke-width="8"><circle cx="300" cy="100" r="70"/><circle cx="300" cy="100" r="42" stroke="#0ea5e9"/></g><circle cx="300" cy="100" r="14" fill="#0f172a"/><path d="M300 100l150-70" stroke="#0f172a" stroke-width="5"/>`,
`<g fill="#fff" stroke="#cbd5e1"><rect x="150" y="20" width="300" height="160" rx="14"/></g><g fill="#0ea5e9"><circle cx="185" cy="60" r="10"/><circle cx="185" cy="100" r="10"/><circle cx="185" cy="140" r="10"/></g><g fill="#cbd5e1"><rect x="210" y="54" width="200" height="12" rx="6"/><rect x="210" y="94" width="160" height="12" rx="6"/><rect x="210" y="134" width="180" height="12" rx="6"/></g>`];
const POSTS=[
{s:'what-is-digital-marketing',c:'Digital Marketing',t:'What Is Digital Marketing? A Simple Guide for Business Owners',e:'A plain-language guide to how digital marketing helps customers find, trust and choose your business.',cta:['Ready to clarify your digital marketing strategy?','Review your current marketing and identify the highest-impact next steps for your business.'],x:`Digital marketing is no longer a “nice to have.” It’s how customers find you, decide if they trust you, and choose whether to work with you. In simple terms, digital marketing is everything you do online to attract, engage, and convert customers—your website, your content, your ads, your social media, and your email.

Unlike traditional marketing, which often feels like shouting into a crowd and hoping someone listens, digital marketing lets you speak directly to the people who are most likely to buy from you. You can target by location, interests, behavior, and even the exact problems they’re trying to solve. More importantly, you can measure what’s working: which ads bring leads, which pages get attention, and which messages actually move people to take action.

For business owners, this changes the game. Instead of guessing whether your marketing is effective, you can see which activities drive real outcomes—calls, bookings, demos, and sales. That clarity allows you to invest more in what works and stop wasting money on what doesn’t.

Most buying journeys now start online, whether someone is looking for a local service, a B2B solution, or an e-commerce product. Before they ever speak to you, they’ve already searched on Google, scanned your website, checked your reviews, and compared you to competitors. If your digital presence is weak or confusing, you lose opportunities before you even have a chance to explain why you’re different.

Strong digital marketing fixes that. It helps you:

- Get found by the right people at the right time
- Build trust before the first conversation
- Turn interest into concrete actions like booked calls or purchases

You don’t need to be everywhere at once. Most successful businesses focus on a few key channels and execute them well.

Your website and SEO form the foundation. A well-optimized site doesn’t just look good; it answers your visitors’ questions, shows clear proof of your value, and guides them toward a specific action. Paid advertising on Google and Meta (Facebook/Instagram) then amplifies your reach, putting your offer in front of people who are actively searching or fit your ideal customer profile. Social media builds awareness and trust over time, while content marketing—blogs, guides, videos—positions you as an authority people want to work with. Email marketing keeps you connected with leads and past customers so you stay top of mind when they’re ready to move.

The businesses that win online aren’t necessarily the ones with the biggest budgets. They’re the ones with the clearest messaging, the most focused strategies, and the discipline to track what matters. If your current efforts feel scattered or you’re not sure where to start, the first step is often a simple, honest review of what you’re doing now and how it ties to your goals.`},
{s:'lead-generation-not-working',c:'Lead Generation',t:'7 Signs Your Lead Generation Strategy Isn’t Working (And What to Do Instead)',e:'Seven warning signs of an underperforming pipeline, and a practical seven-step approach to fix it.',cta:['Want help fixing your lead generation?','Walk through your current approach and design a system that consistently attracts qualified leads.'],x:`Many businesses are busy “doing marketing” but still wake up to an empty pipeline. They run ads, post on social, and maintain a website, yet the phone doesn’t ring and the calendar stays light. The problem usually isn’t effort; it’s strategy. Lead generation only works when the right message reaches the right people through the right channels—and when there’s a clear path from interest to action.

If you’re spending time and money but not seeing quality leads, you’ll often spot a few warning signs.

You might be getting traffic but no leads. Visitors land on your site, scroll a bit, and leave without filling out a form, booking a call, or even emailing you. This usually means your offer isn’t clear, your call to action is weak, or your pages don’t speak directly to your visitor’s problem. People don’t need more information; they need a clear reason to take the next step with you.

Or you might be getting leads, but they’re low quality. They’re too small, not a good fit, or just “shopping around.” This often happens when your targeting is too broad or your messaging tries to appeal to everyone. When you speak to everyone, you resonate with no one. The fix is to get specific about who you serve, what problems you solve, and what results you deliver, then tailor your ads, content, and forms to that ideal profile.

Another red flag is a rising cost per lead. You’re spending more to get each lead over time without better results. This can come from ad fatigue, poor landing page experiences, or unclear offers. Ads that once performed well start to stall, and instead of testing and optimizing, many businesses just increase the budget. The smarter move is to refresh creatives, tighten targeting, and improve the pages where people decide whether to engage.

Relying on a single channel is also risky. If all your leads come from referrals or one ad platform, any change—algorithm updates, budget cuts, market shifts—can dry up your pipeline overnight. Diversifying across a few complementary channels (for example, SEO plus paid ads plus email) makes your lead flow more stable and predictable.

Many businesses also don’t track where leads come from. They can’t tell which campaigns, ads, or content pieces actually drive inquiries. Without that visibility, you can’t double down on what works or cut what doesn’t. Simple tracking—UTM parameters, basic analytics, and a CRM or spreadsheet—can transform your decision-making.

Even when leads do come in, they often go cold because there’s no follow-up system. One email and then silence. No nurture sequence, no structured follow-up, no reminders. In reality, most people don’t buy on first contact. They need time, trust, and repeated value before they’re ready to commit.

Finally, vague or generic messaging kills lead generation. If your website and ads sound like everyone else’s—full of buzzwords and light on specifics—prospects won’t see a reason to choose you. The businesses that stand out speak directly to their niche’s pain points, show clear outcomes, and back it up with proof.

A better approach looks like this:

- Define your ideal customer and their biggest challenges
- Craft one clear, compelling offer that solves a specific problem
- Choose 1–2 primary channels where those customers already spend time
- Build focused landing pages with a single goal and CTA
- Set up basic tracking so you know what’s working
- Nurture leads with simple email sequences and structured follow-up
- Review performance monthly and adjust based on data

If several of these signs feel familiar, it’s a strong signal that your lead generation system needs a redesign, not just more effort.`},
{s:'marketing-funnel-that-converts',c:'Funnels',t:'How to Build a Marketing Funnel That Actually Converts',e:'How to guide prospects from first awareness to decision with a customer-first funnel.',cta:['Want help designing a funnel that fits your business?','Map out a simple, high-converting funnel tailored to your goals and audience.'],x:`A marketing funnel is simply the journey a prospect takes from first hearing about you to becoming a paying customer. But in practice, most funnels don’t convert because they’re built around what the business wants to say, not what the customer needs to hear. A high-converting funnel flips that: it starts with the customer’s problem and guides them step by step toward a solution you provide.

Imagine your ideal customer. They wake up with a challenge—maybe they’re struggling to get qualified leads, their ads aren’t delivering ROI, or their website gets traffic but no inquiries. They turn to Google, social media, or a trusted contact for help. At this stage, they’re not thinking about your company; they’re thinking about their problem. Your funnel’s job is to meet them there, earn their attention, and gradually show them that you understand their situation and have a proven way to fix it.

Most effective funnels move people through a few key stages. First, awareness: they realize they have a problem and start looking for answers. Then interest: they consume content, watch videos, or read posts that help them understand their options. Next, consideration: they compare providers, read case studies, and look for proof. Finally, decision: they take action—book a call, request a quote, or make a purchase. The best funnels don’t stop there; they continue into retention, turning customers into repeat buyers and advocates.

Where many businesses go wrong is trying to push people straight from awareness to decision. They run an ad and send traffic to a generic homepage with no clear next step. Or they ask for a sale before they’ve built any trust. A well-designed funnel respects the customer’s journey and gives them the right information at the right time.

It starts with clarity on who you’re serving. The more specific you are about your ideal customer—their industry, size, role, and pain points—the easier it is to craft messages that resonate. Instead of “We help businesses grow,” you can say, “We help B2B service firms book more qualified sales calls with targeted paid ads and landing pages.” That specificity attracts the right people and filters out the rest.

Next, map out the journey. What question is your prospect asking at each stage? What content or offer helps them move forward? For example, at the awareness stage, a blog post or short video that addresses their main problem works well. At the consideration stage, a case study or detailed guide builds trust. At the decision stage, a clear consultation offer or demo removes friction.

Your funnel assets then bring this journey to life. A focused landing page with one goal—like booking a call or downloading a guide—performs far better than a multipurpose homepage. A strong lead magnet (a checklist, template, or short playbook) gives people a reason to share their contact info. An email nurture sequence keeps the conversation going, sharing value, addressing objections, and gently guiding them toward a conversation. And a clear sales or consultation page explains your process, shows results, and makes it easy to take the next step.

Traffic is what feeds the funnel. You can drive it through organic search, paid ads, social media, email, or referrals. The key is to start with 1–2 channels where your ideal customers already spend time, rather than trying to be everywhere at once. As you learn what works, you can expand.

Finally, measure and optimize. Track how many people click from ads or emails to your landing page, how many convert into leads, and how many of those leads become customers. Use that data to refine your headlines, offers, and targeting. Small improvements at each stage compound into significantly better results over time.

If this feels complex, remember: you don’t need a perfect funnel on day one. You need a clear path from problem to solution, with consistent, helpful touchpoints along the way.`},
{s:'google-ads-vs-meta-ads',c:'Paid Advertising',t:'Google Ads vs. Meta Ads: Which Is Better for Your Business?',e:'Intent-driven search versus attention-driven social ads, and how to choose where to start.',cta:['Not sure which platform fits your business?','Discuss your goals and design a paid ads strategy that matches your audience and budget.'],x:`When business owners think about paid advertising, two platforms usually come up first: Google Ads and Meta Ads (Facebook and Instagram). Both can deliver excellent results, but they work in very different ways. The real question isn’t which platform is “better” in general—it’s which one fits your business, your offer, and your audience right now.

Google Ads are intent-driven. They show your message when people actively search for specific keywords on Google or browse related sites. Someone types “marketing agency near me,” “best CRM for small business,” or “how to get more qualified leads,” and your ad appears at the top of the results. This makes Google Ads especially powerful when there’s clear, existing demand for what you offer. You’re meeting people at the moment they’re looking for a solution.

Meta Ads, on the other hand, are attention-driven. They appear in people’s feeds and stories as they scroll through Facebook or Instagram. Users aren’t necessarily searching for your service; they’re catching up with friends, consuming content, or killing time. Your ad has to interrupt that flow with a compelling message, visual, or video. This makes Meta Ads excellent for building awareness, creating demand, and staying top of mind, especially when your audience spends a lot of time on these platforms.

So when is Google Ads the better fit? If people already search for your type of service, if you offer a clear and specific solution, or if you want to capture high-intent traffic ready to act, Google is often the place to start. It’s particularly strong for local services, niche B2B offerings, and any situation where search volume aligns with your ideal customers’ needs. The upside is high intent and a clear connection between search query and your offer. The downside is that competitive keywords can get expensive, and you need solid landing pages and tracking to make it work.

Meta Ads shine when you need to educate your market or create demand. If your audience doesn’t yet know they need your service, or if your offer benefits from strong visuals and storytelling, Meta can be incredibly effective. It’s also powerful for retargeting—showing ads to people who have already visited your website or engaged with your content. The upside is advanced targeting, often lower cost per impression, and great potential for brand building. The downside is lower intent; people aren’t actively looking to buy, so your creative and messaging have to work harder.

Many businesses don’t have to choose one forever. A common pattern is to use both as part of a broader strategy. Meta Ads build awareness and interest, introducing your brand and driving traffic to your site. Google Ads then capture high-intent searches from people who are ready to move. A prospect might first see your Meta ad, later search on Google for your service, click your Google Ad, and finally book a call. This multi-touch approach often produces the best overall results.

To decide where to start, ask yourself three questions:

- Are people actively searching for what I offer?
- Where does my audience spend most of their time online?
- What’s my main goal right now—immediate leads or long-term brand and demand?

If search intent is strong, Google Ads may give you faster, more direct results. If you need to build awareness and educate your market, Meta Ads might be the better starting point. You can always add the second platform once you’ve validated your message and offer on the first.`},
{s:'website-not-generating-leads',c:'Website & Conversion',t:'Why Your Website Isn’t Generating Leads (And How to Fix It)',e:'Common reasons visitors leave without acting, and a checklist to find your biggest opportunities.',cta:['Want your website to work harder for your business?','Review where your site loses visitors and identify the fixes with the most impact.'],x:`Your website should be one of your best salespeople. It works 24/7, never takes a day off, and can handle countless conversations at once. Yet for many businesses, the website is more like a digital brochure: it looks nice, explains what the company does, and then… nothing. Visitors come, scroll a bit, and leave without taking any action. If your website isn’t generating leads, the issue is rarely the design alone; it’s usually how clearly it speaks to your visitors and guides them toward a decision.

The first problem is often an unclear value proposition. When someone lands on your homepage, they should immediately understand what you do, who you help, and why it matters. Instead, many sites open with vague headlines like “We provide innovative solutions” or long paragraphs about the company’s history. Visitors don’t care about your story yet; they care about their problem. If you don’t quickly show that you understand their situation and can deliver a specific outcome, they’ll move on to someone who does.

Even when the message is clear, many websites fail to give people a clear next step. They have multiple CTAs competing for attention—“Learn More,” “Contact Us,” “Follow Us,” “Download Our Brochure”—or they bury the main CTA at the bottom of the page. Visitors are left wondering, “What should I do now?” A high-converting website chooses one primary action—usually booking a call, requesting a quote, or downloading a valuable resource—and makes that action obvious above the fold and throughout the page.

Another common issue is weak or missing offers. Asking someone to “contact us” with no additional value is a big ask for a first-time visitor. The most effective websites give people a reason to engage right away. That might be a free strategy call, a quick audit, or a useful lead magnet like a checklist, template, or short guide. These offers lower the barrier to entry and start a relationship on a helpful note instead of a salesy one.

User experience also plays a huge role. If your site is slow, confusing, or hard to use on mobile, people bounce before they even see your message. Long load times, cluttered navigation, and dense blocks of text all work against you. A clean, fast, mobile-friendly site with clear headings and short paragraphs keeps visitors engaged long enough to consider your offer.

Social proof is another missing piece on many sites. Prospects want to know that others like them have succeeded with you. Testimonials, case studies, and specific results transform your claims from “we’re great” to “here’s how we’ve helped businesses like yours.” The more concrete your proof—numbers, outcomes, recognizable client names—the more trust you build.

Finally, many websites don’t have a follow-up system. Even the best site won’t convert everyone on the first visit. Without email capture, nurture sequences, or retargeting, you lose the chance to stay in touch with interested visitors. A simple opt-in for a valuable resource, followed by a few helpful emails, can turn a casual visitor into a qualified lead over time.

If you want to quickly assess your own site, ask yourself:

- Is my headline clear, specific, and focused on the visitor’s problem or goal?
- Do I have one primary CTA that’s easy to find and understand?
- Am I offering something valuable in exchange for contact information?
- Is my site fast, simple to navigate, and mobile-friendly?
- Do I show real proof—testimonials, case studies, results?
- Do I have a system to follow up with people who show interest?

If you answered “no” to several of these, you’ve likely found your biggest opportunities.`}];
const rt=p=>Math.max(1,Math.round(p.x.split(/\s+/).length/200))+' min read';
const body=p=>p.x.split(/\n\n+/).map((b,i)=>{const h=b.startsWith('- ')?`<ul>${b.split('\n').map(l=>`<li>${l.slice(2)}</li>`).join('')}</ul>`:`<p>${b}</p>`;return h+(i===2?`<figure class="fig">${sv(MINI[POSTS.indexOf(p)%3],200)}</figure>`:'')}).join('');
pages.blog=()=>`<section class="hero"><div class="w" style="display:block;max-width:900px"><span class="lab">Blog</span><h1>MARKETING INSIGHTS FOR <span class="gt">THE DIGITAL WORLD.</span></h1><p style="font-size:1.1rem">Practical insights, strategies, and educational resources to help businesses understand digital marketing and make smarter decisions.</p></div></section>
<section style="padding-top:20px"><div class="w">${head('Blog purpose','LEARN. APPLY. GROW.','The MARKETIQO blog exists to simplify digital marketing and provide useful knowledge businesses and marketers can apply in the real world.')}<div style="margin:24px 0" id="cf"><button class="pill b on" data-c="">All</button>${[...new Set(POSTS.map(p=>p.c))].map(c=>`<button class="pill b" data-c="${c}">${c}</button>`).join('')}</div><div class="grid" id="pg">${POSTS.map((p,i)=>`<a class="card rv tilt" href="#blog/${p.s}" data-c="${p.c}" style="display:block"><div style="margin-bottom:14px">${sv(ART[i],300)}</div><span class="pill">${p.c}</span><h3>${p.t}</h3><p style="font-size:.92rem">${p.e}</p><div class="meta">${rt(p)} · Sep 2026</div><span class="btn o sm" style="margin-top:14px">Read article</span></a>`).join('')}</div></div></section>`;
const article=s=>{const i=POSTS.findIndex(p=>p.s===s),p=POSTS[i],n=POSTS[(i+1)%POSTS.length];return`<article class="w art-p"><a href="#blog" class="lab" style="margin-top:36px">← All articles</a><span class="pill">${p.c}</span><h1 style="font-size:clamp(1.9rem,4.4vw,3rem)">${p.t}</h1><div class="meta" style="margin-bottom:24px">MARKETIQO · ${rt(p)} · Sep 2026</div><figure class="fig">${sv(ART[i],300)}</figure><div class="prose">${body(p)}</div><div class="cta" style="margin:40px 0"><h3 style="font-size:1.5rem;color:#fff">${p.cta[0]}</h3><p style="max-width:520px;margin:0 auto 22px">${p.cta[1]}</p><a class="btn mag" href="#contact">Book a Free Consultation</a></div><a class="card" href="#blog/${n.s}" style="display:block;margin-bottom:60px"><span class="lab">Next article →</span><h3 style="margin:0">${n.t}</h3></a></article>`};
function heroReveal(){const h=$('.hero.full .w>div:first-child');if(h)h.classList.add('show')}
let miqIntroDone=sessionStorage.getItem('miq_intro');
function go(){
 const [h,sub]=(location.hash||'#home').slice(1).split('/'),k=pages[h]?h:'home';
 $('#app').innerHTML=`<div class="page">${k==='blog'&&POSTS.some(p=>p.s===sub)?article(sub):pages[k]()}</div>`;
 document.querySelectorAll('.links a').forEach(a=>a.classList.toggle('on',a.getAttribute('href')==='#'+k));
 $('#ln').classList.remove('o');scrollTo(0,0);fx();
 const cf=$('#cf');if(cf)cf.onclick=e=>{const b=e.target.closest('button');if(!b)return;cf.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));document.querySelectorAll('#pg .card').forEach(c=>c.style.display=!b.dataset.c||c.dataset.c===b.dataset.c?'':'none')};
 const f=$('#f');if(f)f.onsubmit=submitForm;
 if(k==='home'){
  if(!miqIntroDone && !matchMedia('(prefers-reduced-motion:reduce)').matches){
   miqIntroDone=1;sessionStorage.setItem('miq_intro','1');
   const ov=document.createElement('div');ov.className='intro';
   ov.innerHTML='<div class="il"><b>&#10022;</b> MARKETIQO</div>';
   document.body.appendChild(ov);document.body.style.overflow='hidden';
   requestAnimationFrame(()=>requestAnimationFrame(()=>ov.classList.add('in')));
   setTimeout(()=>{ov.classList.add('out');document.body.style.overflow='';heroReveal();setTimeout(()=>ov.remove(),650)},1500);
  }else heroReveal();
 }
}

$('#mb').onclick=()=>$('#ln').classList.toggle('o');
addEventListener('hashchange',go);go();

async function submitForm(e){
  e.preventDefault();
  const f=e.target,btn=f.querySelector('button[type=submit]'),er=$('#ferr'),label=btn.textContent;
  er.style.display='none';btn.disabled=true;btn.textContent='Sending…';
  try{
    const r=await fetch((window.API_BASE||'')+'/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(f)))});
    const j=await r.json().catch(()=>({}));
    if(!r.ok)throw new Error(j.error||'Something went wrong. Please try again.');
    f.style.display='none';$('#ok').classList.add('s');
  }catch(x){er.textContent=x.message;er.style.display='block'}
  finally{btn.disabled=false;btn.textContent=label}
}


if(!matchMedia('(prefers-reduced-motion:reduce)').matches){
 document.addEventListener('mousemove',e=>{
  const el=e.target.closest('.card,.btn,.st .dot,.fn,.pill.b');
  if(!el)return;
  const r=el.getBoundingClientRect();
  el.style.setProperty('--gx',((e.clientX-r.left)/r.width*100)+'%');
  el.style.setProperty('--gy',((e.clientY-r.top)/r.height*100)+'%');
 },{passive:true});
}
